--- #YAML:1.0
name:               Games-Word-Wordlist-SGB
version:            2010091501
abstract:           Wordlist from the Stanford GraphBase.
author:
    - Abigail <cpan@abigail.be>
license:            mit
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
    strict:               0
    Test::More:           0.88
    warnings:             0
build_requires:
    ExtUtils::MakeMaker:  0
    strict:               0
    Test::More:           0.88
    warnings:             0
requires:
    Games::Word::Wordlist:  0
    List::MoreUtils:      0
    perl:                 5.006
    strict:               0
    Test::Deep::NoTest:   0
    warnings:             0
resources:
    repository:  git://github.com/Abigail/Games--Word--Wordlist--SGB.git
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
keywords:
    - words
    - list
    - wordlist
    - word list
    - Stanford GraphBase
test_requires:
    strict:      0
    Test::More:  0.88
    warnings:    0
